ioos/bio_mobilization_workshop

_episodes/03-data-cleaning.md

Trying to add in code snippets to the data cleaning section.

adding code example snippets to data cleaning section

---

setup.md

adding basic guidance

---

CONTRIBUTING.md
README.md

cleaning up various pieces of main

cleaning up main

---

CITATION.cff

Citation should be good with these changes.

updating the citation closes #30

---

_includes/custom-schedule.html

Add QAQC page

---

_config.yml
_extras/edna-extension.md

starting edna page

---

_episodes/02-break.md
_episodes/03-data-cleaning.md
_episodes/04-create-schema.md
_episodes/05-break.md

added image credits for xkcd comics and GBIF extensions diagram.

adding image credits

---

_episodes/06-qa-qc.md

Do not merge this yet. Simply starting my changes and will merge when ready.

Qaqc updates

---

index.md

closes #58
it would be better if we created a new `_includes/bdm` directory with an intro.html which contains all this info in html and we reference in index.md https://github.com/ioos/bio_mobilization_workshop/blob/4a675cd275a091a026ad6210f6a0fed2164ade2b/index.md?plain=1#L94-L100
But who has time for that??

updating index

---

index.md

I copied names over from [the spreadsheet](https://docs.google.com/spreadsheets/d/1RlFR4WMlzqdmykefJ7-J0wA8Y0CB13uXMWuXLc7Mwn0/edit?usp=sharing).
This will probably need updating as we firm up who will be instructing & volunteering.
I didn't put any thought into the order of names.

+ organizers & volunteers from spreadsheet

---

_includes/custom-schedule.html

should look something like this now.

adding breakouts to schedule

---

_episodes/04-create-schema.md

* added text explanations about how measurement data is flattened to measurementType, measurementUnit, and measurementValue. also added discussion of the associated IDs.
* changed schema figure
<details>
<summary><strong>Instructions</strong></summary>
Thanks for contributing! :heart:
If this contribution is for instructor training, please email the link to this contribution to
instructor.training@carpentries.org so we can record your progress. You've completed your contribution
step for instructor checkout by submitting this contribution!
Keep in mind that **lesson maintainers are volunteers** and it may take them some time to
respond to your contribution. Although not all contributions can be incorporated into the lesson
materials, we appreciate your time and effort to improve the …

adding measurementTypeID info

---

_episodes/06-qa-qc.md

updating main checks
adjusting bottom tip

updates post 3/31 meeting

---

_episodes/06-qa-qc.md

adding link in qa/qc to intro required terms table

---

_config.yml
_includes/custom-schedule.html
_includes/workshop_calendar.html
index.md

closes:
* #98 
* #101 
* #100 
* #99 
We still need to decide on:
1. who the POC should be
2. the final schedule

starting initial updates for 2024 event

---

_episodes/08-post-workshop.md

Before merging we need to update the new link for the 2024 post-workshop survey.

minor improvements for 2024

---

_episodes/07-validation-and-publishing.md

Minor changes to validation-and-publishing.md

Minor changes to 07-validation-and-publishing.md

---

_includes/custom-schedule.html

Proposed change to make `Animal Telemetry` in the schedule actionable.

Making Animal Telemetry in schedule actionable

---

index.md

Added instructors and helpers in alphabetically order. Feel free to rearrange.

Updated instructors and helpers

---

_includes/custom-schedule.html

closes #125
@timvdstap Schedule table is now fixed and animal telemetry is hyperlinked

fixing schedule table and hyperlink to animal telemetry

---

index.md

Included two additional helpers in the list of helpers on the main page.

Included two additional helpers
